import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import Wrapper from "@/components/base/Wrapper";
import Modal from "@/components/common/Modal";
import Providers from "@/components/base/Providers";
import Toast from "@/components/common/Toast";
const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create your portfolio",
  description: "Generated by tanuj",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className} flex flex-col min-h-screen `}
      >
        <Providers>
        <Modal />
        <Toast />
        {/* <Providers>
          <Navbar />
          <Toast />
          <Modal/>
          <main className="flex-1 w-full justify-center items-center">
            {children}
          </main>
          <Footer />
        </Providers> */}
        <Wrapper>
          {children}
        </Wrapper>
        </Providers>
      </body>
    </html>
  );
}
